### ISSUE TITLE
Make example work on linux

### ISSUE THREAD

**Issue by shahawi-sumup** [gfcwfzkm/gshell#1]
Hi @gfcwfzkm 

Thanks for providing such tiny shell with this easy implementation.

I will share here how did i make it work on linux and it is quite simple.
1. install libncruses `sudo apt-get install libncurses5-dev`
2. Change the following lines in `main.c`:
```patch
-#include <conio.h>             // Function 'getch'
+#include <curses.h>

-               u16CmdRetVal = gshell_processShell((char)getch());
+               u16CmdRetVal = gshell_processShell((char)getchar());
```
3. `gcc ./main.c ./gshell.c -ltinfo -lncurses`

**Comment by gfcwfzkm** [comment]
Thank you for your addition!  I will test it and adapt the code to choose your addition on linux systems.

**Comment by gfcwfzkm** [comment]
Added your code changes so the demo works on both windows and linux.
