### ISSUE TITLE
License

### ISSUE THREAD

**Issue by estutzenberger** [gfcwfzkm/gshell#2]
Hi, I'm using this library for a project and I was wondering if you could add a license to it. I'd suggest something like the MIT license:
https://en.wikipedia.org//wiki/MIT_License

Also, here's a Github doc on how to easily add a license to the repo:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by gfcwfzkm** [comment]
Hi!

Thanks for reminding me to add an license to my project. I'll review the options and add a license today.

**Comment by estutzenberger** [comment]
Appreciate it. This has been very useful for a small embedded project I've been working on so thank you for the effort!

**Comment by gfcwfzkm** [comment]
I am likely going for the GNU LGPLv2.1 license, as it doesn't seem as restrictive as GPLv2 or v3 to projects that are libraries, while still mandating to document the changes done to the original library.

I'm up for discussion if you have more experience in the field of licenses or think that a different license might be more suitable. My experience with licenses is limited to ~30min of research on choosealicense.com

**Comment by estutzenberger** [comment]
The main difference between LGPL and a license like MIT, in my experience, is that LGPL enforces that changes to the library are released as source (only the library and not the full source of works which use the library) where as MIT does not have such an enforcement. Generally speaking, I'd say this is a personal choice for you to make and that LGPL seems line a valid option.

**Comment by gfcwfzkm** [comment]
Thanks for the feedback, I'm glad to read that I did understood the differences between the two licenses correctly.

My main reasoning is to get feedback & source if changes to the library are done, in order to maintain those changes back into the library if I think that it is a good option.

I'll close the issue then. Thanks for bringing it up!
